<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>YoloSharpOnnx</Title>
		<PackageProjectUrl>https://github.com/meloht/YoloSharpOnnx</PackageProjectUrl>
		<RepositoryUrl>https://github.com/meloht/YoloSharpOnnx</RepositoryUrl>
		<PackageTags>yolo5;yolo8;yolo9;yolo10;yolo11;yolo12;yolo26;yolo;yoloe;yolo-world;rt-detr;object-detection;image-classification;instance-segmentation;pose-estimation;obb-detection;opencv;csharp;onnx;onnx-runtime;cross-platform;cpu;cuda;gpu;tensorrt;coreml;directml;computer-vision</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>YoloSharpOnnx is a high performance, memory reuse, cross-platform, production-ready C# YOLO inference library base on OpenCV and ONNX Runtime.</Description>
		<Authors>meloht</Authors>
		<Version>3.2.2</Version>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Copyright>Copyright © meloht</Copyright>
		<PackageReleaseNotes>YoloSharpOnnx 3.2.2 ThrowIfDisposed improvements</PackageReleaseNotes>
		<PackageIcon>YoloSharpOnnx.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\imgs\YoloSharpOnnx.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md" Link="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.26.0" />
		<PackageReference Include="OpenCvSharp4" Version="4.13.0.20260528" />
	</ItemGroup>

</Project>
